### ISSUE TITLE
Filter for iter_entries() don't work

### ISSUE THREAD

**Issue by profhccaesar** [nyantec/clockodo.py#2]
There's a small typo in the code which prevent the filter from working.

E. g.:

```python
entries = clockodoApi.iter_entries(
    time_since = fromDtTm, 
    time_until = toDtTm,
    filters={ 'users_id' : 54759 })
```
The limitation on the employee is ignored.

Have a look into entry.py at line 275:

```python
        for k, v in filters.items():
            if k in ["customer", "project", "service"]:
                params[f"filters[{k}s_id]"] = v.id
            else:
                if isinstance(v, bool):
                    v = str(int(v))
                params[f"filters[{k}]"] = v
```
Clockodo's keyword is `filter`, not `filters`. Just removing the additional "s" from the code and the application works as expected.

See attached patch-File.
[filter-iter-entries_patch.txt](https://github.com/nyantec/clockodo.py/files/10769476/filter-iter-entries_patch.txt)

**Comment by vikanezrimaya** [comment]
Thank you for noticing this issue! I applied your patch as-is and credited you in the commit message.
